import logging
import trafilatura
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter
from shared.schemas import ContentType

logger = logging.getLogger(__name__)

class ContentExtractionAgent:
    
    def extract_youtube(self, video_id: str) -> str:
        """
        Get transcript for a video.
        """
        try:
            # Modern usage: list_transcripts -> find -> fetch
            from youtube_transcript_api import YouTubeTranscriptApi
            
            transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
            
            # Try fetching manually created first, then generated
            # Supports English or English-autogenerated
            # We can iterate or just find generic 'en'
            
            try:
                # Prefer manually created English
                transcript = transcript_list.find_manually_created_transcript(['en'])
            except:
                try:
                    # Fallback to generated English
                    transcript = transcript_list.find_generated_transcript(['en'])
                except:
                    # Fallback to any English (might be translated?) or just first available
                    try:
                        transcript = transcript_list.find_transcript(['en'])
                    except:
                        # Fallback: Just take the first one available (e.g. video is in Spanish)
                        # We might want to translate it? For now, just take it.
                        transcript = next(iter(transcript_list))

            # Fetch the actual data
            transcript_data = transcript.fetch()
            
            formatter = TextFormatter()
            return formatter.format_transcript(transcript_data)
            
        except Exception as e:
            logger.error(f"YouTubeTranscriptApi failed: {e}. Trying yt-dlp fallback.")
            return self.extract_with_ytdlp(video_id)

    def extract_with_ytdlp(self, video_id: str) -> str:
        """
        Fallback: Use yt-dlp to download auto-generated subs and read them.
        """
        import subprocess
        import os
        import glob
        
        url = f"https://www.youtube.com/watch?v={video_id}"
        # Download subs, no video, convert to vtt (text-like)
        cmd = [
            "yt-dlp",
            "--write-auto-sub",
            "--skip-download",
            "--sub-lang", "en,en-orig",
            "--convert-subs", "vtt",
            "--output", f"/tmp/{video_id}",
            url
        ]
        
        try:
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
            # Read the file (yt-dlp might name it /tmp/id.en.vtt)
            files = glob.glob(f"/tmp/{video_id}*.vtt")
            if files:
                with open(files[0], 'r') as f:
                    content = f.read()
                
                # Cleanup
                for f in files:
                    os.remove(f)
                    
                # Simple VTT cleanup (remove timestamps)
                # This is a crude cleaner, but better than nothing
                lines = content.splitlines()
                text_lines = []
                seen = set()
                for line in lines:
                    if '-->' in line or line.strip() == '' or line.startswith('WEBVTT'):
                        continue
                    # remove tags like <c.color...>
                    import re
                    clean_line = re.sub(r'<[^>]+>', '', line).strip()
                    if clean_line and clean_line not in seen:
                        text_lines.append(clean_line)
                        seen.add(clean_line)
                
                return " ".join(text_lines)
                
            return ""
        except Exception as e:
            logger.error(f"yt-dlp fallback failed: {e}")
            return ""

    def extract_web_text(self, url: str) -> str:
        """
        Extract main text from a webpage (Reddit, Article) using Trafilatura.
        """
        try:
            downloaded = trafilatura.fetch_url(url)
            if downloaded:
                text = trafilatura.extract(downloaded)
                return text if text else ""
            return ""
        except Exception as e:
            logger.error(f"Error extracting text from {url}: {e}")
            return ""

    def extract(self, url: str, source_type: ContentType, source_id: str = None) -> str:
        if source_type == ContentType.YOUTUBE:
            # Try to extract video ID from URL if not provided
            vid = source_id
            if not vid:
                if "v=" in url:
                    vid = url.split("v=")[1].split("&")[0]
                elif "youtu.be" in url:
                    vid = url.split("/")[-1]
            
            if vid:
                return self.extract_youtube(vid)
            else:
                logger.error(f"Could not determine Video ID for {url}")
                return ""
        
        else:
            return self.extract_web_text(url)
